package numbers;

public class NumberException extends Exception {
	static final long serialVersionUID = 293;
	public enum ErrorCode {
		INVALID_INPUT_FORMAT,
		BAD_NUMBER,
		BAD_ARGUMENTS,
		BAD_NUMBER_INPUT,
		AMBIGUOUS_NUMBER
	}
	
	private final ErrorCode errorCode;
	/**
	 * Autogenerated.
	 * @return the errorCode
	 */
	public final ErrorCode getErrorCode() {
		return errorCode;
	}
	
	NumberException(ErrorCode errorCode){
		this.errorCode = errorCode;
	}
	
	public String toString() {
		return "NumberException " + errorCode;
	}
}
